'use client';

import { useParams } from 'next/navigation';
import { mockAIReports, mockPatients } from '../../../../src/data/mockData';
import { FileText, AlertTriangle, Calendar, TrendingUp, TrendingDown, CheckCircle, Clock } from 'lucide-react';

export default function AIReportViewer() {
  const { reportId } = useParams();
  
  const report = mockAIReports.find(r => r.id === reportId as string);
  const patient = report ? mockPatients.find(p => p.mrn === report.mrn) : undefined;
  
  if (!report) {
    return (
      <div className="space-y-6">
        <h1 className="text-3xl text-gray-900">Report Not Found</h1>
        <p className="text-gray-600">The requested AI report could not be found.</p>
      </div>
    );
  }
  
  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'Critical': return 'bg-red-100 text-red-700 border-red-200';
      case 'High': return 'bg-orange-100 text-orange-700 border-orange-200';
      case 'Moderate': return 'bg-yellow-100 text-yellow-700 border-yellow-200';
      case 'Low': return 'bg-green-100 text-green-700 border-green-200';
      default: return 'bg-gray-100 text-gray-700 border-gray-200';
    }
  };

  return (
    <div className="space-y-6">
      {/* Report Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl text-gray-900 mb-2">AI Report</h1>
          <p className="text-gray-600">Detailed analysis generated by our AI system</p>
        </div>
        <div className="flex items-center space-x-2">
          <span className={`px-3 py-1 rounded-full text-sm border ${getSeverityColor(report.severity)}`}>
            {report.severity} Severity
          </span>
          <span className={`px-3 py-1 rounded-full text-sm ${
            report.status === 'New' ? 'bg-blue-100 text-blue-800' : 
            report.status === 'In Progress' ? 'bg-yellow-100 text-yellow-800' : 
            'bg-green-100 text-green-800'
          }`}>
            {report.status}
          </span>
        </div>
      </div>

      {/* Patient Info Card */}
      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <div className="flex items-center">
          <div className="w-12 h-12 bg-blue-600 rounded-full flex items-center justify-center text-white font-medium">
            {patient?.name.charAt(0) || report.patientName.charAt(0)}
          </div>
          <div className="ml-4">
            <h2 className="text-lg font-medium text-gray-900">{report.patientName}</h2>
            <p className="text-sm text-gray-500">MRN: {report.mrn} • {patient?.gender || 'Unknown'} • {patient ? calculateAge(patient.dob) : 'N/A'}</p>
          </div>
          <div className="ml-auto flex items-center text-sm text-gray-500">
            <Clock className="w-4 h-4 mr-1" />
            <span>Submitted: {new Date(report.submittedTime).toLocaleString()}</span>
          </div>
        </div>
      </div>

      {/* AI Analysis */}
      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <div className="flex items-center mb-4">
          <FileText className="w-6 h-6 text-blue-600 mr-2" />
          <h2 className="text-xl text-gray-900">AI Analysis</h2>
        </div>
        <div className="prose max-w-none">
          <p className="text-gray-700">{report.aiAnalysis}</p>
        </div>
      </div>

      {/* Vital Signs */}
      {report.vitalSigns && (
        <div className="bg-white rounded-xl border border-gray-200 p-6">
          <div className="flex items-center mb-4">
            <TrendingUp className="w-6 h-6 text-green-600 mr-2" />
            <h2 className="text-xl text-gray-900">Vital Signs</h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="border border-gray-200 rounded-lg p-4 text-center">
              <div className="text-2xl font-bold text-gray-900">{report.vitalSigns.heartRate}</div>
              <div className="text-sm text-gray-500">Heart Rate (bpm)</div>
            </div>
            <div className="border border-gray-200 rounded-lg p-4 text-center">
              <div className="text-2xl font-bold text-gray-900">{report.vitalSigns.bloodPressure}</div>
              <div className="text-sm text-gray-500">Blood Pressure</div>
            </div>
            <div className="border border-gray-200 rounded-lg p-4 text-center">
              <div className="text-2xl font-bold text-gray-900">{report.vitalSigns.temperature}°F</div>
              <div className="text-sm text-gray-500">Temperature</div>
            </div>
            <div className="border border-gray-200 rounded-lg p-4 text-center">
              <div className="text-2xl font-bold text-gray-900">{report.vitalSigns.oxygenSaturation}%</div>
              <div className="text-sm text-gray-500">Oxygen Saturation</div>
            </div>
          </div>
        </div>
      )}

      {/* Recommendations */}
      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <div className="flex items-center mb-4">
          <CheckCircle className="w-6 h-6 text-green-600 mr-2" />
          <h2 className="text-xl text-gray-900">AI Recommendations</h2>
        </div>
        <ul className="space-y-2">
          {report.recommendations.map((rec, index) => (
            <li key={index} className="flex items-start">
              <div className="shrink-0 mt-1">
                <div className="w-2 h-2 bg-blue-600 rounded-full"></div>
              </div>
              <span className="ml-3 text-gray-700">{rec}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* Action Buttons */}
      <div className="flex justify-end space-x-3">
        <button className="px-6 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors">
          Download PDF
        </button>
        <button className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
          Approve Report
        </button>
      </div>
    </div>
  );
}

function calculateAge(dob: string): string {
  const birthDate = new Date(dob);
  const today = new Date();
  let age = today.getFullYear() - birthDate.getFullYear();
  const monthDiff = today.getMonth() - birthDate.getMonth();
  
  if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
    age--;
  }
  
  return `${age} years`;
}